version: '3'

services:
  nginx: # 配置nginx依赖
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - redis-cluster
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cluster1
      - cluster2

  cluster1: # 第一个spring boot镜像
    image: buse/springboot-cluster
    networks:
      - redis-cluster
    environment: # 配置spring boot的环境变量
      SPRING_REDIS_HOST: redis-docker
      SPRING_REDIS_PASSWORD: dockerRedis
      SPRING_REDIS_PORT: 6379
      SERVER_ID: cluster1
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis-docker

  cluster2: # 第二个spring boot镜像
    image: buse/springboot-cluster
    networks:
      - redis-cluster
    environment: # 配置spring boot的环境变量
      SPRING_REDIS_HOST: redis-docker
      SPRING_REDIS_PASSWORD: dockerRedis
      SPRING_REDIS_PORT: 6379
      SERVER_ID: cluster2
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis-docker

  redis-docker: # 配置redis
    image: redis
    volumes:
      - /Users/buse/Downloads/redis/data:/data
    entrypoint: redis-server --appendonly yes --requirepass "dockerRedis"
    networks:
      - redis-cluster
    ports:
      - "6379:6379"

networks: # 创建此集群使用的网络
  redis-cluster: